### ISSUE TITLE
`ImportError: cannot import name 'get_terminal_size' from 'click.termui'`

### ISSUE THREAD

**Issue by paw-lu** [paw-lu/nbpreview#525]
### What happened?

`ImportError: cannot import name 'get_terminal_size' from 'click.termui'` when trying to use Typer. See https://github.com/tiangolo/typer/pull/375. This issue arises on Click 8.1.0.

Need to pin Click right now <8.1.0 to solve, then later update Typer when fix is merged.

### nbpreview version

0.8.1

**Comment by tiangolo** [comment]
Hello! I just released Typer `0.4.1` that should handle this. :rocket: :nerd_face:

**Comment by paw-lu** [comment]
Thanks a bunch for the heads up @tiangolo, and thanks for Typer!
